### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by bubnenkoff** [vladdeSV/scone#4] opened 2016-10-11 06:28 UTC
```
> dub                                                                                                                        
Fetching scone 1.2.0 (getting selected version)...                                                                           
Placing scone 1.2.0 to C:\Users\bubenkov_di\AppData\Roaming\dub\packages\...                                                 
Performing "debug" build using dmd for x86.                                                                                  
scone 1.2.0: building configuration "library"...                                                                             
app ~master: building configuration "application"...                                                                         
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\scone-1.2.0\scone\source\scone\console\ui\package.d(3,15): Error: module ba
se is in file 'scone\console\ui\base.d' which cannot be read                                                                 
import path[0] = source                                                                                                      
import path[1] = C:\Users\bubenkov_di\AppData\Roaming\dub\packages\scone-1.2.0\scone\source                                  
import path[2] = C:\D\dmd2\windows\bin\..\..\src\phobos                                                                      
import path[3] = C:\D\dmd2\windows\bin\..\..\src\druntime\import                                                             
dmd failed with exit code 1.                       
```

**Comment by vladdeSV** [comment] 2016-10-11 07:37
This is odd. There is indeed no file called scone/console/ui/base.d, however the the file scone/console/ui/ui_base.d, with the module name `module scone.console.ui.base;` does.

I do not understand why this error occurs. I will look into it 👍🏼

**Comment by vladdeSV** [comment] 2016-10-11 07:45
It would be helpful if you, and for all future issues you open, tell what OS + architecture, and compiler version

**Comment by bubnenkoff** [comment] 2016-10-11 07:46
x32 D Compiler v2.071.2
Windows 7 x64

**Comment by vladdeSV** [comment] 2016-10-11 18:51
What version of dub are you using?

**Comment by bubnenkoff** [comment] 2016-10-17 09:32
DUB version 1.0.0, built on Jun 20 2016

**Comment by DanSze** [comment] 2016-10-17 15:48
It looks like the underlying issue is that dub takes a convention over configuration approach when compiling dependencies. Specifically, when compiling the project, it includes all of the source files for the project, but only the modules imported for external dependencies. Since there's no way to know which file has which module without compiling the file, it assumes the module name corresponds to the file path.

Renaming the files to base.d works as a temporary fix.

**Comment by vladdeSV** [comment] 2016-10-17 17:43
That is very strange. I am running Windows 10, x64 with DMD32 D Compiler v2.071.1 and DUB version 1.0.0, built on Jun 20 2016. I definitely get no errors, and Travis passes the build.

I will check around. **To be continued...**

**Comment by vladdeSV** [comment] 2016-10-17 17:44
Reason to why the module name and file name differ is because the documentation overwrites files with the same name 😢

**Comment by vladdeSV** [comment] 2016-10-21 11:03
I cannot reproduce this error on my Windows 7 latop.
```
$ dub
Fetching scone 1.2.0 (getting selected version)...
Placing scone 1.2.0 to C:\Users\v\AppData\Roaming\dub\packages\...
Performing "debug" build using dmd for x86.
scone 1.2.0: building configuration "library"...
test-ddd ~master: building configuration "application"...
Linking...
Running .\test-ddd.exe
Edit source/app.d to start your project.
```
 I have no idea why this happens to your computer.

**Comment by bubnenkoff** [comment] 2016-10-25 18:14
http://img.ctrlv.in/img/16/10/21/5809f9f0c7664.png

2016-10-21 14:13 GMT+03:00 Dmitry Bubnenkov <bubnenkoff@gmail.com>:

**Comment by vladdeSV** [comment] 2016-10-25 18:23
Heyo, none of the images exist. Could you reupload them on, for instance, imgur?

**Comment by bubnenkoff** [comment] 2016-10-25 18:31
One moment I will try again. Now I have this issue
http://img.ctrlv.in/img/16/10/21/5809f82d3298e.png

2016-10-21 14:03 GMT+03:00 Vladde Nordholm <notifications@github.com>:

**Comment by vladdeSV** [comment] 2016-10-27 17:23
Once again, the image http://img.ctrlv.in/img/16/10/21/5809f82d3298e.png **does not exists**. I cannot view it.

Please re-upload it 👍

**Comment by bubnenkoff** [comment] 2016-10-27 17:30
Sorry, I will do it's later. Nothing spatial just same error with output
compiler and dub version.

2016-10-27 20:23 GMT+03:00 Vladde Nordholm <notifications@github.com>:

**Comment by vladdeSV** [comment] 2017-02-19 00:19
Closing because lack of interest from issuer

**Closed by vladdeSV** 2017-02-19 00:19 UTC
