### ISSUE TITLE
progress bar?

### ISSUE THREAD

**Issue by bubnenkoff** [vladdeSV/scone#2] opened 2016-08-30 13:37 UTC
is it's possible with scone?

**Comment by vladdeSV** [comment] 2016-08-30 14:26
It certainly is possible. Although there is no built-in support for progressbars, you could implement https://gist.github.com/vladdeSV/802a7215268cfc6bbf72 yourself.

Simply update a label with the string returned from gistfile above.

**Comment by vladdeSV** [comment] 2016-08-31 12:34
If you feel this has been resolved, feel free to close this issue :smile:

**Comment by bubnenkoff** [comment] 2016-09-14 06:04
Thanks for link, but it's look like it's need some external code (probably API calls) to get terminal width.

**Comment by vladdeSV** [comment] 2016-09-14 07:04
You can get the console size with https://github.com/vladdeSV/scone/blob/master/source/scone/window.d#L57

**Comment by bubnenkoff** [comment] 2016-09-14 07:08
Could you explain how this function works?
```
auto windowSize() @property
{
    int[2] ret;
    version(Windows) ret = win_windowSize;
    return ret;
}
```

It's do not like winapi. What is it? What about posix?

**Comment by vladdeSV** [comment] 2016-09-14 10:02
Sadly scone is not cross platform, and only works for Windows.

The function calls the windows api and returns the size as an `int[2]`

**Comment by bubnenkoff** [comment] 2016-09-14 10:05
Could you show what WinApi function it's calling? Just for better
understanding of code.

2016-09-14 13:02 GMT+03:00 Vladde Nordholm <notifications@github.com>:

**Comment by rjmcguire** [comment] 2016-09-14 10:10
For unix with termios: http://man7.org/linux/man-pages/man4/tty_ioctl.4.html

On Wed, Sep 14, 2016 at 12:05 PM, Dmitry Bubnenkov <notifications@github.com

**Comment by vladdeSV** [comment] 2016-09-14 12:07
Once upon a time there was partial support for POSIX, however, due to problems with input, I scrapped it. The code used for terminal size was https://github.com/vladdeSV/scone/blob/old-posix/source/scone/posix/posix_terminal.d#L45

@bubnenkoff If you follow the function, you end up at https://github.com/vladdeSV/scone/blob/master/source/scone/windows/win_console.d#L77

**Comment by vladdeSV** [comment] 2016-10-02 09:05
The issue at hand seems to be the lack of POSIX support. Sadly there are no plans to support POSIX.

Progressbars are not built-in, but can be manually constructed. If you feel the issue is solved, feel free to close it 👍

**Comment by vladdeSV** [comment] 2016-10-06 12:00
I added progress bars, available in the next release

**Closed by vladdeSV** 2016-10-06 12:00 UTC
Labels: help wanted
